spring.application.name=backend

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://yogeshsingh09:yogeshsingh09@cluster0.38oaghi.mongodb.net/kisansetu?retryWrites=true&w=majority&appName=Cluster0

# Server Port
server.port=8080

# JWT Config
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Logging
logging.level.org.springframework.data.mongodb=INFO
